@ICT302_BackendAPI_HostAddress = http://localhost:5173

GET {{ICT302_BackendAPI_HostAddress}}/api/test/
Accept: application/json

GET {{ICT302_BackendAPI_HostAddress}}/api/db/animal
Accept: application/json

###
