name: Backend Docker Deploy

on:   
  push:
    # Publish `dev` as Docker `latest` image.
    branches:
      - dev
  
  # Manual run
  workflow_dispatch:

env:
  IMAGE_NAME: brycestandley/ict302-backend
  
jobs:
  Build_Docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Build image
        working-directory : ./Backend API/ICT302-BackendAPI/
        run: docker build . -t $IMAGE_NAME:latest

      - name: List Images
        run: docker images

      - name: Push image
        run: |
          echo IMAGE_NAME=$IMAGE_NAME
          docker push ghcr.io/$IMAGE_NAME
