name: Backend Docker Deploy

on:   
  push:
    # Publish `dev` as Docker `latest` image.
    branches:
      - dev
  
  # Manual run
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.repository_owner }}/ict302-backend

jobs:
  Build_Docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Build image
        working-directory : ./Backend API/ICT302-BackendAPI/
        run: docker build . --tag $IMAGE_NAME

      - name: Push image
        working-directory : ./Backend API/ICT302-BackendAPI/
        run: |
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_NAME | tr '[A-Z]' '[a-z]')
          VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker push ghcr.io/$IMAGE_ID:$VERSION
